# Form implementation generated from reading ui file 'CIFAR10_class.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(529, 441)
        Dialog.setStyleSheet("*{\n"
"    font-size:16px;\n"
"}")
        self.label_result = QtWidgets.QLabel(parent=Dialog)
        self.label_result.setGeometry(QtCore.QRect(250, 270, 81, 21))
        self.label_result.setObjectName("label_result")
        self.label_pred = QtWidgets.QLabel(parent=Dialog)
        self.label_pred.setGeometry(QtCore.QRect(250, 360, 81, 21))
        self.label_pred.setObjectName("label_pred")
        self.pushButton_input = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_input.setGeometry(QtCore.QRect(280, 30, 201, 23))
        self.pushButton_input.setObjectName("pushButton_input")
        self.pushButton_run = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_run.setGeometry(QtCore.QRect(280, 150, 201, 23))
        self.pushButton_run.setObjectName("pushButton_run")
        self.graphicsView_input = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView_input.setGeometry(QtCore.QRect(10, 20, 261, 221))
        self.graphicsView_input.setObjectName("graphicsView_input")
        self.plainTextEdit_result = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_result.setGeometry(QtCore.QRect(360, 270, 151, 21))
        self.plainTextEdit_result.setObjectName("plainTextEdit_result")
        self.plainTextEdit_pred = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_pred.setGeometry(QtCore.QRect(360, 360, 151, 21))
        self.plainTextEdit_pred.setObjectName("plainTextEdit_pred")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "三叶青十分类器"))
        self.label_result.setText(_translate("Dialog", "识别结果"))
        self.label_pred.setText(_translate("Dialog", "识别准确率"))
        self.pushButton_input.setText(_translate("Dialog", "导入图片"))
        self.pushButton_run.setText(_translate("Dialog", "识别运行"))
